package com.andreborud.thecoachtimer.data.model

import android.os.Parcelable
import kotlinx.android.parcel.IgnoredOnParcel
import kotlinx.android.parcel.Parcelize

// PlayerSession made parcelable to be able to send it with an intent from SessionActivity to SyncJobIntentService
@Parcelize
data class PlayerSession(
    val fullName: String,
    val laps: Int,
    val peakSpeed: Double,
    val lapTimes: LongArray
): Parcelable {

    // Ignoring id in the parcel isn't a problem as this id is used internally for
    // the db and when sent to the server a new one would probably be generated
    @IgnoredOnParcel
    var id: Int = 0

    // Autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as PlayerSession

        if (fullName != other.fullName) return false
        if (laps != other.laps) return false
        if (peakSpeed != other.peakSpeed) return false
        if (!lapTimes.contentEquals(other.lapTimes)) return false
        if (id != other.id) return false

        return true
    }

    // Autogenerated
    override fun hashCode(): Int {
        var result = fullName.hashCode()
        result = 31 * result + laps
        result = 31 * result + peakSpeed.hashCode()
        result = 31 * result + lapTimes.contentHashCode()
        result = 31 * result + id
        return result
    }
}
